---
abstract: 'subtest output to a flatten'
author:
  - 'xaicron <xaicron {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.96
  Test::SharedFork: 0.16
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Flatten
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  bugtracker: https://github.com/xaicron/p5-Test-Flatten/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/xaicron/p5-Test-Flatten
version: 0.01
