---
abstract: 'subtest output to a flatten'
author:
  - 'xaicron <xaicron {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::More: '0.96'
  Test::Requires: '0.06'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.3, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Flatten
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Test::Flatten:
    file: lib/Test/Flatten.pm
    version: '0.10'
resources:
  bugtracker: https://git@github.com/xaicron/p5-Test-Flatten/issues
  homepage: https://git@github.com/xaicron/p5-Test-Flatten
  repository: git://git@github.com/xaicron/p5-Test-Flatten.git
version: '0.10'
x_contributors:
  - 'Hiroyoshi Houchi <git@hixi-hyi.com>'
  - 'xaicron <xaicron@gmail.com>'
